// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAhiIG22GHW0u7HLH0LaDl1DeV0M5C86A',
    appId: '1:755001541202:android:9d677b983faf705808d58b',
    messagingSenderId: '755001541202',
    projectId: 'conge-project-418f3',
    authDomain: 'conge-project.firebaseapp.com',
    storageBucket: 'conge-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAhiIG22GHW0u7HLH0LaDl1DeV0M5C86A',
    appId: '1:755001541202:android:9d677b983faf705808d58b',
    messagingSenderId: '755001541202',
    projectId: 'conge-project-418f3',
    storageBucket: 'conge-project-418f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAhiIG22GHW0u7HLH0LaDl1DeV0M5C86A',
    appId: '1:755001541202:android:9d677b983faf705808d58b',
    messagingSenderId: '755001541202',
    projectId: 'conge-project-418f3',
    storageBucket: 'conge-project-418f3.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAhiIG22GHW0u7HLH0LaDl1DeV0M5C86A',
    appId: '1:755001541202:android:9d677b983faf705808d58b',
    messagingSenderId: '755001541202',
    projectId: 'conge-project-418f3',
    storageBucket: 'conge-project-418f3.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAhiIG22GHW0u7HLH0LaDl1DeV0M5C86A',
    appId: '1:755001541202:android:9d677b983faf705808d58b',
    messagingSenderId: '755001541202',
    projectId: 'conge-project-418f3',
    authDomain: 'conge-project.firebaseapp.com',
    storageBucket: 'conge-project-418f3.appspot.com',
  );
}
